# Generated by Django 3.2.4 on 2021-08-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multi',
            fields=[
                ('multi_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_type', models.CharField(max_length=32)),
                ('nec', models.BooleanField()),
                ('title', models.CharField(max_length=128)),
                ('context_num', models.IntegerField()),
                ('context_1', models.CharField(max_length=128)),
                ('context_2', models.CharField(max_length=128)),
                ('context_3', models.CharField(max_length=128)),
                ('context_4', models.CharField(max_length=128)),
                ('context_5', models.CharField(max_length=128)),
                ('context_6', models.CharField(max_length=128)),
                ('context_7', models.CharField(max_length=128)),
                ('context_8', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_type', models.CharField(max_length=32)),
                ('nec', models.BooleanField()),
                ('title', models.CharField(max_length=128)),
                ('pack_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_type', models.CharField(max_length=32)),
                ('nec', models.BooleanField()),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('single_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_type', models.CharField(max_length=32)),
                ('nec', models.BooleanField()),
                ('title', models.CharField(max_length=128)),
                ('context_num', models.IntegerField()),
                ('correct_id', models.IntegerField()),
                ('context_1', models.CharField(max_length=128)),
                ('context_2', models.CharField(max_length=128)),
                ('context_3', models.CharField(max_length=128)),
                ('context_4', models.CharField(max_length=128)),
                ('context_5', models.CharField(max_length=128)),
                ('context_6', models.CharField(max_length=128)),
                ('context_7', models.CharField(max_length=128)),
                ('context_8', models.CharField(max_length=128)),
            ],
        ),
    ]
