# Generated by Django 3.2.4 on 2021-08-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multi',
            old_name='context_1',
            new_name='content_1',
        ),
        migrations.RenameField(
            model_name='multi',
            old_name='context_2',
            new_name='content_2',
        ),
        migrations.RenameField(
            model_name='multi',
            old_name='context_3',
            new_name='content_3',
        ),
        migrations.RenameField(
            model_name='multi',
            old_name='context_4',
            new_name='content_4',
        ),
        migrations.RenameField(
            model_name='multi',
            old_name='context_5',
            new_name='content_5',
        ),
        migrations.RenameField(
            model_name='multi',
            old_name='context_6',
            new_name='content_6',
        ),
        migrations.RenameField(
            model_name='multi',
            old_name='context_7',
            new_name='content_7',
        ),
        migrations.RenameField(
            model_name='multi',
            old_name='context_8',
            new_name='content_8',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_1',
            new_name='content_1',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_2',
            new_name='content_2',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_3',
            new_name='content_3',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_4',
            new_name='content_4',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_5',
            new_name='content_5',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_6',
            new_name='content_6',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_7',
            new_name='content_7',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='context_8',
            new_name='content_8',
        ),
        migrations.RemoveField(
            model_name='multi',
            name='context_num',
        ),
        migrations.RemoveField(
            model_name='single',
            name='context_num',
        ),
    ]
