# Generated by Django 3.2.4 on 2021-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_single_correct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='correct_id',
            field=models.IntegerField(null=True),
        ),
    ]
