# Generated by Django 3.2.4 on 2021-08-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_single_correct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='multi',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='single',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
