# Generated by Django 3.2.4 on 2021-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20210827_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_id', models.IntegerField()),
                ('pre_id', models.IntegerField()),
                ('pre_content_1', models.BooleanField()),
                ('pre_content_2', models.BooleanField(null=True)),
                ('pre_content_3', models.BooleanField(null=True)),
                ('pre_content_4', models.BooleanField(null=True)),
                ('pre_content_5', models.BooleanField(null=True)),
                ('pre_content_6', models.BooleanField(null=True)),
                ('pre_content_7', models.BooleanField(null=True)),
                ('pre_content_8', models.BooleanField(null=True)),
            ],
        ),
    ]
