# Generated by Django 3.2.4 on 2021-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_sequence_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='single',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
