# Generated by Django 3.2.4 on 2021-08-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20210828_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='multi',
            name='is_apply',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multi',
            name='is_exam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='is_apply',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='is_exam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='is_apply',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='is_exam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='single',
            name='is_apply',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='single',
            name='is_exam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
