# Generated by Django 3.2.4 on 2021-08-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20210828_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multi',
            old_name='content_9_leave',
            new_name='content_8_leave',
        ),
    ]
