from django.db import models


class Single(models.Model):
    single_id = models.AutoField(primary_key=True)
    que_type = models.CharField(max_length=32)
    nec = models.BooleanField()
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=128, null=True)
    content_1 = models.CharField(max_length=128)
    content_1_isTrue = models.BooleanField(null=True)
    content_1_leave = models.IntegerField(null=True)
    content_2 = models.CharField(max_length=128)
    content_2_isTrue = models.BooleanField(null=True)
    content_2_leave = models.IntegerField(null=True)
    content_3 = models.CharField(max_length=128)
    content_3_isTrue = models.BooleanField(null=True)
    content_3_leave = models.IntegerField(null=True)
    content_4 = models.CharField(max_length=128)
    content_4_isTrue = models.BooleanField(null=True)
    content_4_leave = models.IntegerField(null=True)
    content_5 = models.CharField(max_length=128)
    content_5_isTrue = models.BooleanField(null=True)
    content_5_leave = models.IntegerField(null=True)
    content_6 = models.CharField(max_length=128)
    content_6_isTrue = models.BooleanField(null=True)
    content_6_leave = models.IntegerField(null=True)
    content_7 = models.CharField(max_length=128)
    content_7_isTrue = models.BooleanField(null=True)
    content_7_leave = models.IntegerField(null=True)
    content_8 = models.CharField(max_length=128)
    content_8_isTrue = models.BooleanField(null=True)
    content_8_leave = models.IntegerField(null=True)
    score = models.IntegerField(null=True)
    is_apply = models.BooleanField()
    is_exam = models.BooleanField()


class Multi(models.Model):
    multi_id = models.AutoField(primary_key=True)
    que_type = models.CharField(max_length=32)
    nec = models.BooleanField()
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=128, null=True)
    content_1 = models.CharField(max_length=128)
    content_1_isTrue = models.BooleanField(null=True)
    content_1_leave = models.IntegerField(null=True)
    content_2 = models.CharField(max_length=128)
    content_2_isTrue = models.BooleanField(null=True)
    content_2_leave = models.IntegerField(null=True)
    content_3 = models.CharField(max_length=128)
    content_3_isTrue = models.BooleanField(null=True)
    content_3_leave = models.IntegerField(null=True)
    content_4 = models.CharField(max_length=128)
    content_4_isTrue = models.BooleanField(null=True)
    content_4_leave = models.IntegerField(null=True)
    content_5 = models.CharField(max_length=128)
    content_5_isTrue = models.BooleanField(null=True)
    content_5_leave = models.IntegerField(null=True)
    content_6 = models.CharField(max_length=128)
    content_6_isTrue = models.BooleanField(null=True)
    content_6_leave = models.IntegerField(null=True)
    content_7 = models.CharField(max_length=128)
    content_7_isTrue = models.BooleanField(null=True)
    content_7_leave = models.IntegerField(null=True)
    content_8 = models.CharField(max_length=128)
    content_8_isTrue = models.BooleanField(null=True)
    content_9_leave = models.IntegerField(null=True)
    score = models.IntegerField(null=True)
    is_apply = models.BooleanField()
    is_exam = models.BooleanField()


class Pack(models.Model):
    pack_id = models.AutoField(primary_key=True)
    que_type = models.CharField(max_length=32)
    nec = models.BooleanField()
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=128, null=True)
    pack_num = models.IntegerField()
    pack_ans_1 = models.CharField(max_length=128, null=True)
    pack_ans_2 = models.CharField(max_length=128, null=True)
    pack_ans_3 = models.CharField(max_length=128, null=True)
    pack_ans_4 = models.CharField(max_length=128, null=True)
    pack_ans_5 = models.CharField(max_length=128, null=True)
    score = models.IntegerField(null=True)
    is_apply = models.BooleanField()
    is_exam = models.BooleanField()


class Rate(models.Model):
    rate_id = models.AutoField(primary_key=True)
    que_type = models.CharField(max_length=32)
    nec = models.BooleanField()
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=128, null=True)
    is_apply = models.BooleanField()
    is_exam = models.BooleanField()


class Sequence(models.Model):
    sequence_id = models.AutoField(primary_key=True)
    list_id = models.IntegerField(null=True)
    que_id = models.IntegerField()
    pre_id = models.IntegerField()
    pre_content_1 = models.BooleanField(null=True)
    pre_content_2 = models.BooleanField(null=True)
    pre_content_3 = models.BooleanField(null=True)
    pre_content_4 = models.BooleanField(null=True)
    pre_content_5 = models.BooleanField(null=True)
    pre_content_6 = models.BooleanField(null=True)
    pre_content_7 = models.BooleanField(null=True)
    pre_content_8 = models.BooleanField(null=True)
