# Generated by Django 3.2.4 on 2021-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
