# Generated by Django 3.2.4 on 2021-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20210821_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='full_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
