# Generated by Django 3.2.4 on 2021-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20210822_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='need_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='list',
            name='only_once',
            field=models.BooleanField(default=True),
        ),
    ]
