# Generated by Django 3.2.4 on 2021-08-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20210822_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='publish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
