# Generated by Django 3.2.4 on 2021-08-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_list_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='need_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='only_once',
            field=models.BooleanField(default=False),
        ),
    ]
