# Generated by Django 3.2.4 on 2021-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20210824_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='need_login',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='only_once',
            field=models.BooleanField(),
        ),
    ]
