# Generated by Django 3.2.6 on 2021-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20210824_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='code',
            field=models.CharField(default='abcdefgh', max_length=64),
            preserve_default=False,
        ),
    ]
